AllCops:
  Exclude:
    - 'Guardfile'
    - 'homework_tester/**/*'
    
Documentation:
  Enabled: False

Style/FormatString:
  EnforcedStyle: sprintf
  SupportedStyles:
    - format
    - sprintf
    - percent
